"""criar_tabelas_iniciais

Revision ID: 7606e3e0f60a
Revises: 
Create Date: 2026-02-25 17:52:50.071854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7606e3e0f60a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fornecedor',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('razao_social', sa.String(length=150), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("cnpj ~ '^\\d{14}$'", name='ck_fornecedor_cnpj_numerico'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('produto',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('ncm', sa.String(length=8), nullable=True),
    sa.Column('unidade_comercial', sa.String(length=10), nullable=False),
    sa.Column('requer_validade', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('estoque',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('produto_id', sa.Uuid(), nullable=False),
    sa.Column('localizacao', sa.String(length=10), nullable=False),
    sa.Column('validade', sa.Date(), nullable=True),
    sa.Column('quantidade', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantidade >= 0', name='ck_estoque_quantidade_positiva'),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_estoque_com_validade', 'estoque', ['produto_id', 'localizacao', 'validade'], unique=True, postgresql_where='validade IS NOT NULL')
    op.create_index('uq_estoque_sem_validade', 'estoque', ['produto_id', 'localizacao'], unique=True, postgresql_where='validade IS NULL')
    op.create_table('movimentacao',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('produto_id', sa.Uuid(), nullable=False),
    sa.Column('localizacao', sa.String(length=10), nullable=False),
    sa.Column('validade', sa.Date(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('valor_unitario', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("tipo NOT IN ('AJUSTE_ENTRADA', 'AJUSTE_SAIDA') OR motivo IS NOT NULL", name='ck_movimentacao_motivo_ajuste'),
    sa.CheckConstraint('quantidade > 0', name='ck_movimentacao_quantidade_positiva'),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produto_fornecedor',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('produto_id', sa.Uuid(), nullable=False),
    sa.Column('fornecedor_id', sa.Uuid(), nullable=False),
    sa.Column('codigo_fornecedor', sa.String(length=60), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedor.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('produto_id', 'fornecedor_id', name='uq_produto_fornecedor')
    )
    # Trigger de atualização automática de estoque
    op.execute("""
        CREATE OR REPLACE FUNCTION fn_atualizar_estoque()
        RETURNS TRIGGER AS $$
        DECLARE
            v_delta NUMERIC(12, 3);
        BEGIN
            IF NEW.tipo IN ('ENTRADA', 'AJUSTE_ENTRADA') THEN
                v_delta := NEW.quantidade;
            ELSE
                v_delta := NEW.quantidade * -1;
            END IF;

            UPDATE estoque
            SET
                quantidade    = quantidade + v_delta,
                atualizado_em = NOW()
            WHERE
                produto_id  = NEW.produto_id
                AND localizacao = NEW.localizacao
                AND validade IS NOT DISTINCT FROM NEW.validade;

            IF NOT FOUND THEN
                IF v_delta < 0 THEN
                    RAISE EXCEPTION
                        'Tentativa de reduzir estoque inexistente. Produto: %, Local: %, Validade: %',
                        NEW.produto_id, NEW.localizacao, NEW.validade;
                END IF;

                INSERT INTO estoque (produto_id, localizacao, validade, quantidade)
                VALUES (NEW.produto_id, NEW.localizacao, NEW.validade, v_delta);
            ELSE
                IF (
                    SELECT quantidade FROM estoque
                    WHERE produto_id    = NEW.produto_id
                      AND localizacao   = NEW.localizacao
                      AND validade IS NOT DISTINCT FROM NEW.validade
                ) < 0 THEN
                    RAISE EXCEPTION
                        'Saldo insuficiente. Produto: %, Local: %, Validade: %',
                        NEW.produto_id, NEW.localizacao, NEW.validade;
                END IF;
            END IF;

            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)

    op.execute("""
        CREATE TRIGGER trg_atualizar_estoque
            AFTER INSERT ON movimentacao
            FOR EACH ROW
            EXECUTE FUNCTION fn_atualizar_estoque();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS trg_atualizar_estoque ON movimentacao")
    op.execute("DROP FUNCTION IF EXISTS fn_atualizar_estoque")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produto_fornecedor')
    op.drop_table('movimentacao')
    op.drop_index('uq_estoque_sem_validade', table_name='estoque', postgresql_where='validade IS NULL')
    op.drop_index('uq_estoque_com_validade', table_name='estoque', postgresql_where='validade IS NOT NULL')
    op.drop_table('estoque')
    op.drop_table('usuario')
    op.drop_table('produto')
    op.drop_table('fornecedor')
    # ### end Alembic commands ###
