"""criar_tabela_nfe_importada

Revision ID: d900a0189f55
Revises: c515d1d6f17c
Create Date: 2026-03-04 23:02:09.329791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd900a0189f55'
down_revision: Union[str, Sequence[str], None] = 'c515d1d6f17c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nfe_importada',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chave_acesso', sa.String(length=44), nullable=False),
    sa.Column('fornecedor_cnpj', sa.String(length=14), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chave_acesso')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nfe_importada')
    # ### end Alembic commands ###
